version: '3.3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/core:/etc/nginx/conf.d
            - ./../htdocs:/var/www/
            - ./nginx/logs:/var/log/nginx/
            - ./nginx/html:/usr/share/nginx/html/
        environment:
            APP_DIR: ${APP_DIR}
            DOLLAR: ${DOLLAR}
            DOMAIN: ${DOMAIN}
            PHP_PORT: ${PHP_PORT}
        links:
            - php
        depends_on:
            - php
            - mysql
    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./mysql:/var/lib/mysql
    php:
        build:
            context: ./php
            args:
                - CURRENT_UID=${CURRENT_UID}
                - CURRENT_GID=${CURRENT_GID}
                - APP_DIR=${APP_DIR}

        container_name: php-fpm
        user: '${CURRENT_UID}:${CURRENT_GID}'
        environment:
            TIMEZONE: ${TIMEZONE}
            PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
        volumes:
            - ./../htdocs:/var/www

        links:
            - mysql
        depends_on:
            - mysql