version: '3.8'

services:
  app:
    container_name: laravel-app
    build: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - mysql_db
    networks:
      - laravel

  web:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql_db:
    container_name: laravel-mysql-db
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: AdM!n1234*
      MYSQL_DATABASE: vue_admin
    ports:
      - 3307:3306
    networks:
      - laravel

  phpmyadmin:
    container_name: laravel-phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_HOST=mysql_db
      - PMA_PORT=3306
    depends_on:
      - mysql_db
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
